services:
  campusmgmtsystem:
    image: pavithrakongara/myimage   # replace with your app image
    container_name: campus_app
    ports:
      - "7079:8080"
    depends_on:
      - mongodb
    environment:
      MONGO_URL: "mongodb://mongodb:27017/campusdb"

  mongodb:
    image: mongo:6.0
    container_name: campus_mongo
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data: